services:
  tmdb-addon:
    image: ghcr.io/aves-omni/tmdb-addon:latest
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 3000:3000
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://127.0.0.1:3000"]
      interval: 5s
      timeout: 2s
      retries: 10
    depends_on:
      tmdb-addon_redis:
        condition: service_healthy

  tmdb-addon_redis:
    image: redis:8.0.2-alpine
    restart: unless-stopped
    volumes:
      - ./cache:/data
    command: redis-server --appendonly yes --save 60 1
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 2s
      retries: 10